// Create a user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "first_name": "Chris",
    "last_name": "Hildebrand",
    "username": "childebrand",
    "email": "childebrand94@gmail.com"

}

###
// Create a user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "first_name": "Brandon",
    "last_name": "Hildebrand",
    "username": "bhildebrand",
    "email": "bhildebrand94@gmail.com"

}

###
// Update user 
PUT http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

{
    "first_name": "Steven",
    "last_name": "Hildebrand",
    "username": "StevenTheExample",
    "email": "StevenTheExample@gmail.com"

}


###
//Create a post 
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "url": "www.test.com"
}

###
//Create a post 
POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "url": "www.post2.com"
}


###
// Create a comment 
POST http://localhost:3000/posts/1/comments HTTP/1.1
content-type: application/json

{
    "authorID": 1,
    "message": "What a great post"
}

###
//Create a comment on a comment 
POST http://localhost:3000/posts/1/comments HTTP/1.1
content-type: application/json

{
    "authorID": 1,
    "parentID": 4,
    "message": "What a great comment"
}

###
//Gety all users
GET http://localhost:3000/users HTTP/1.1

###
//get all posts and comments
GET https://micro-reddit-backend.onrender.com/posts HTTP/1.1

###
// get all comments on a post 
GET http://localhost:3000/posts/1/comments

###
// get post by id 
GET http://localhost:3000/posts/6

###
// add vote to post 
// hard coded user id 
PUT http://localhost:3000/posts/1/up-vote HTTP/1.1

###
PUT http://localhost:3000/posts/6/comments/6/up-vote HTTP/1.1